### ISSUE TITLE
RoStrap Package Manager Not Loading

### ISSUE THREAD

**Issue by bryce-happel-walton** [RoStrap/Libraries#27]
The RoStrap Package Manager plugin does not load. It will show the loading animation indefinitely.

**Comment by mutex-lock** [comment]
I'm having the same problem

**Comment by calum-s** [comment]
same

**Comment by intergrav** [comment]
same

**Comment by SpiralAPI** [comment]
Hello! I can confirm this is still an issue. Also, I get the error 
`HTTP 404 (Not Found)https://raw.githubusercontent.com/EmeraldSlash/RbxReady/master/Ready.lua`, I assume this means that RbxReady by EmeraldSlash was removed or privated, and the fact it isn't loading is causing an issue.

**Comment by Your-God** [comment]
I'm getting the same error as well. Was kinda looking forwards to this :\

The last update came out quite awhile ago.. is this project dead?

**Comment by devinkid1** [comment]
Here is a fixed package manager made by nana_kon:
https://www.roblox.com/library/5454792841/RoStrap-Package-Manager

**Comment by bryce-happel-walton** [comment]
It would appear this project is dead, or at least won't be getting any attention any time soon. Rest in pepperoni...
